ci: compare built version of C++ executable vs python package (#263)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,9 +43,21 @@ jobs:
           git config --global --add safe.directory $(pwd)  # make git work inside container.
           mkdir build
           cd build
-          cmake -DRMG_BUILD_EXAMPLES=1 -DBUILD_TESTING=ON -DRMG_BUILD_DOCS=OFF ..
-          make
-          make install
+          cmake -DRMG_BUILD_EXAMPLES=1 -DBUILD_TESTING=ON -DRMG_BUILD_DOCS=OFF .. | tee -a build.log
+          make | tee -a build.log
+          make install | tee -a build.log
+
+      - name: check version equality
+        run: |
+          cd build
+          cpp_version=$(sed -En "s/-- remage version [0-9.]+ \(([0-9a-z.+_-]+)\)/\\1/p" build.log)
+          py_version=$(sed -En "s/-- Installed python wrapper Version: ([0-9a-z.+_-]+)/\\1/p" build.log)
+          if [ "$cpp_version" != "$py_version" ]; then
+            echo "::error::version numbers of python wrapper ($py_version) and cpp executable ($cpp_version) differ!"
+            exit 1
+          else
+            echo "::notice::version numbers of python wrapper ($py_version) and cpp executable ($cpp_version) are matching!"
+          fi
 
       - name: Setup and start xvfb (enables Geant4 visualization)
         run: |
