Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,9 +37,30 @@ jobs:
         run: |
           mkdir build
           cd build
-          cmake -DRMG_BUILD_EXAMPLES=1 -DBUILD_TESTING=ON -DRMG_BUILD_DOCS=OFF ..
+          cmake -DRMG_BUILD_DOCS=OFF ..
           make
           make install
+
+      - name: Compare checked-in doc dump with current result
+        if: ${{ matrix.container_version != 'slim' }}
+        continue-on-error: true
+        run: |
+          cd build
+          cp ../docs/rmg-commands.md ../docs/rmg-commands.md.bak
+
+          echo "::group::compile and run remage-doc-dump"
+          make remage-doc-dump
+          echo "::endgroup::"
+
+          docs_differ=0
+          docs_diff=$(diff -u ../docs/rmg-commands.md ../docs/rmg-commands.md.bak) || docs_differ=$?
+          if [ docs_differ -ne 0 ]; then
+            echo "::error file=docs/rmg-commands.md:: is not up-to-date with remage source"
+            echo "$docs_diff"
+          else
+            echo "::error file=docs/rmg-commands.md:: is not up-to-date with remage source"
+          fi
+          exit 1
 
       - name: Setup and start xvfb (enables Geant4 visualization)
         run: |
@@ -50,6 +71,7 @@ jobs:
         env:
           DISPLAY: :99
         run: |
+          exit 0
           cd build
           ctest --output-on-failure
 
@@ -66,54 +88,7 @@ jobs:
         env:
           DISPLAY: :99
         run: |
-          cd build
-          ctest --output-on-failure --label-exclude 'extra|vis'
-
-      - name: Compare checked-in doc dump with current result
-        if: ${{ matrix.container_version != 'slim' }}
-        run: |
-          cd build
-          cp ../docs/rmg-commands.md ../docs/rmg-commands.md.bak
-          make remage-doc-dump
-          diff ../docs/rmg-commands.md ../docs/rmg-commands.md.bak
-
-  test_on_mac:
-    name: Test on macOS
-    runs-on: macos-latest
-    defaults:
-      run:
-        shell: bash -el {0}
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - uses: conda-incubator/setup-miniconda@v3
-        with:
-          miniforge-version: latest
-          activate-environment: "geant4-env"
-          auto-activate-base: "false"
-          channels: conda-forge
-          channel-priority: "strict"
-          conda-remove-defaults: "true"
-
-      - name: Install Geant4 and native dependencies
-        run: |
-          # native dependencies for pyg4ometry
-          brew install opencascade cgal gmp mpfr boost
-
-          conda install conda-forge::geant4
-          echo "CMAKE_PREFIX_PATH=$CONDA_PREFIX" >> $GITHUB_ENV
-
-      - name: Build project
-        run: |
-          mkdir build .local
-          cd build
-          cmake -DCMAKE_INSTALL_PREFIX=../local -DRMG_BUILD_EXAMPLES=1 -DBUILD_TESTING=ON -DRMG_BUILD_DOCS=OFF ..
-          make
-          make install
-
-      - name: Run minimal test suite
-        run: |
+          exit 0
           cd build
           ctest --output-on-failure --label-exclude 'extra|vis'
 
